CREATE SCHEMA CLOCKIT AUTHORIZATION "PUC";


CREATE TABLE MONITOR(
    Nome VARCHAR(80) NOT NULL,
    PRIMARY KEY(Nome)
);



CREATE TABLE CURSO(
    Nome VARCHAR(20) NOT NULL,
    PRIMARY KEY(Nome)
);


CREATE TABLE DISCIPLINA(
    Nome VARCHAR(30) NOT NULL,
    Periodo INT,
    CursoNome VARCHAR(20) NOT NULL,
    PRIMARY KEY(Nome, CursoNome),
    FOREIGN KEY(CursoNome) REFERENCES CURSO(Nome) ON DELETE CASCADE
);



CCREATE TABLE EVENTO(
    Id INT NOT NULL,
    Recorrente VARCHAR(100),
    LocalEvento VARCHAR(20),
    DataEvento DATE NOT NULL,
    HoraInicio TIME NOT NULL,
    HoraFim TIME,
    DisciplinaSigla VARCHAR(10) NOT NULL,
    PRIMARY KEY(Id),
    FOREIGN KEY(DisciplinaSigla) REFERENCES DISCIPLINA(Sigla)
);


CREATE TABLE MONITOR_EVENTO(
    MonitorNome VARCHAR(80) NOT NULL,
    EventoId INT NOT NULL,
    PRIMARY KEY(MonitorNome, EventoId),
    FOREIGN KEY(MonitorNome) REFERENCES MONITOR(Nome) ON DELETE CASCADE,
    FOREIGN KEY(EventoId) REFERENCES EVENTO(Id) ON DELETE CASCADE
);