CREATE SCHEMA IF NOT EXISTS TECHMENTOR AUTHORIZATION "PUC";

CREATE TABLE MONITOR(
    Nome VARCHAR(80) NOT NULL,
    CONSTRAINT PK_MONITOR PRIMARY KEY (Nome)
);

CREATE TABLE CURSO(
    Nome VARCHAR(20) NOT NULL,
    CONSTRAINT PK_CURSO PRIMARY KEY (Nome)
);

CREATE TABLE DISCIPLINA(
    Sigla VARCHAR(10) NOT NULL,
    Nome VARCHAR(30) NOT NULL,
    Periodo INTEGER,
    CursoNome VARCHAR(20) NOT NULL,
    CONSTRAINT PK_DISCIPLINA PRIMARY KEY (Sigla, CursoNome),
    CONSTRAINT FK_DISCIPLINA_CURSO 
        FOREIGN KEY (CursoNome) 
        REFERENCES CURSO(Nome) 
        ON DELETE CASCADE
);

CREATE TABLE EVENTO(
    Id SERIAL PRIMARY KEY,
    Recorrente VARCHAR(100),
    LocalEvento VARCHAR(20),
    DataEvento DATE NOT NULL,
    HoraInicio TIME NOT NULL,
    HoraFim TIME,
    DisciplinaSigla VARCHAR(10) NOT NULL,
    CursoNome VARCHAR(20) NOT NULL,
    CONSTRAINT FK_EVENTO_DISCIPLINA 
        FOREIGN KEY (DisciplinaSigla, CursoNome) 
        REFERENCES DISCIPLINA(Sigla, CursoNome)
);

CREATE TABLE MONITOR_EVENTO(
    MonitorNome VARCHAR(80) NOT NULL,
    EventoId INTEGER NOT NULL,
    CONSTRAINT PK_MONITOR_EVENTO PRIMARY KEY (MonitorNome, EventoId),
    CONSTRAINT FK_MONITOREVENTO_MONITOR 
        FOREIGN KEY (MonitorNome) 
        REFERENCES MONITOR(Nome) 
        ON DELETE CASCADE,
    CONSTRAINT FK_MONITOREVENTO_EVENTO 
        FOREIGN KEY (EventoId) 
        REFERENCES EVENTO(Id) 
        ON DELETE CASCADE
);